---
title: "tw to world"
output: html_document
---


```{r}
library(ggmap)
data.port=read.table(file="C:/Users/TSR/Desktop/高統r/airports.dat",sep=",")
data.line=read.table(file="C:/Users/TSR/Desktop/高統r/routes .dat",sep=",")
library(stringr)

portintw <- str_detect(data.port[,'V4'], "Taiwan")
twport <- data.port[portintw,]

data.port= data.port[,c('V3','V5','V7','V8','V9')]
names(data.port) <- c('city','code','lan','lon','att')


twport <-twport[twport$V5!='',
                      c('V3','V5','V7','V8','V9')]
names(twport) <- c('city','code','lan','lon','att')

lineintw <- data.line[,'V3'] %in% twport$code 
twline <- data.line[lineintw,c('V3','V5','V9')]

outport=data.port[data.port$code  %in% twline[,"V5"],]

names(twline) <- c('source','destination','equipment')
 

findposition <- function(code) {
    find <- twport$code==code
    x <- twport[find,'lon']
    y <- twport[find,'lan']
    return(data.frame(x,y))
}
 
too <- function(code) {
    find <- data.port$code==code
    x <- data.port[find,'lon']
    y <- data.port[find,'lan']
    return(data.frame(x,y))
}


from <- lapply(as.character(twline$source),findposition)
from <- do.call('rbind',from)
from$group <- 1:dim(from)[1]
names(from) <- c('lon','lan','group')
 
to <- lapply(as.character(twline$destination),too)
to <- do.call('rbind',to)
to$group <-1:dim(to)[1]
names(to) <-c('lon','lan','group')
data.line <- rbind(from,to)

ggmap(get_googlemap(center = 'taiwan', zoom=3,size=c(1800,1200),
                    maptype='roadmap'),extent='device')+
    geom_point(data=twport,aes(x=lon,y=lan),
               colour = 'red4',alpha=0.8)+
  geom_point(data=outport,aes(x=lon,y=lan),
               colour = 'red4',alpha=0.8)+
    geom_line(data=data.line,aes(x=lon,y=lan,group=group),
              size=0.1,alpha=1,color='red4')


```



```{r, echo=FALSE}

```


