---
title: "svm"
output: html_document
---



```{r}

datainput=function(max,goal){
  data=c()
  index1=c()
  index2=c()
    for (i in 0:9){
      aa=paste(goal,i,"_",0:num[i+1],".txt",sep="")
      bb=rep(i,num[i+1]+1)
      cc=0:num[i+1]
      index1=c(index1,bb)
      index2=c(index2,cc)
      data=c(data,aa)
    }
#############製作所有目錄，並記錄檔案編號到index1 ,index2
  xx=matrix(0,ncol=32*32+2,nrow=length(data))
    for (i in 1:length(data)){
      x=readLines(data[i])
      x1=strsplit(x,split="")
      x1=unlist(x1)
      x1=as.numeric(x1)
      xx[i,3:1026]=x1
    }
  xx[,1]=index1
  xx[,2]=index2
  return(xx)
}
##############xx 為第一行是編號0~9 第二行為第二個編號  第三行到第1026行是將該個資料的data 以數值存入


#########讀入資料
num=c(188,197,194,198,185,186,194,200,179,203)
train=datainput(max=num,goal="C:\\Users\\TSR\\Desktop\\文字辨識\\trainingDigits\\")
num=c(86,96,91,84,113,107,86,95,90,88)
test=datainput(max=num,goal="C:\\Users\\TSR\\Desktop\\文字辨識\\testDigits\\")
######建立一個函數，將32*32筆資料，分成8組，分別另為x1~x8，並記錄每組內1的個數
trans=function(max,data,newname,sp){
  newname=matrix(0,ncol=sp+1,nrow=max)
  newname[,1]=data[,1]
  for (j in 1:max){
    for (i in 1:sp){
      newname[j,i+1]=sum(data[j,(32*32/sp*(i-1)+2):(32*32/sp*i+1)])
    }
  }
  newname=as.data.frame(newname)
  names(newname)=c("index1",paste("x",1:sp,sep=""))
  return(newname)
}
#######將資料進行轉換
newtrain=trans(dim(train)[1],train,newtrain,32)
newtest=trans(dim(test)[1],test,newtest,32)

###將0~9換成factor類型，否則後面會有問題
newtrain[,1]=as.factor(newtrain[,1])
newtest[,1]=as.factor(newtest[,1])
library(e1071)
#####建立預測模型  以每列加總值當作x變數
model=svm(index1~.,data=newtrain)
####預測
predict=predict(model,newtest[,2:dim(newtest)[2]])

######以每列加總當作x變數下的正確率
sum(predict==newtest[,1])/length(test[,1])
```
###以每列加總當作x變數下的正確率
```{r}

################將原始資料丟入svm判別
newtrain=as.data.frame(train[,-2])
newtest=as.data.frame(test[,-2])

newtrain[,1]=as.factor(newtrain[,1])
newtest[,1]=as.factor(newtest[,1])
colnames(newtrain)=c("index",paste("x",1:1024,sep=""))
colnames(newtest)=c("index",paste("x",1:1024,sep=""))
library(e1071)
#####建立預測模型
model=svm(index~.,data=newtrain)
model
####預測
predict=predict(model,newtest[,2:dim(newtest)[2]])
######以每筆資料當作x變數的正確率
sum(predict==newtest[,1])/length(test[,1])
```
###以每筆資料當作x變數的正確率



