---
title: "time seriers"
output: html_document
---


```{r}
library(TSA)
x=read.table(file="C:\\Users\\TSR\\Desktop\\時間序列\\4444.txt")

cc=x$V3
cc

###原型
plot.ts(cc,type="o")
acf(cc)
pacf(cc)
####
```



```{r}

###處理季節效應
cc1=diff(log(cc),lag=4)
plot.ts(cc1)

acf(cc1,lag.max=30)

pacf(cc1,lag.max=30)
eacf(cc1)

mse=list()
###ar5
m1=arima(cc,order=c(5,0,0),seasonal=list(order=c(0,1,0),period=4))
m1
fitted(m1)
plot(cc,col="red",type="l")
lines(fitted(m1),col="blue")
plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')


mse[1][1]=sum((unlist(m1[8]))^2)/length(cc)

####
m1=arima(cc,order=c(1,0,0),seasonal=list(order=c(0,1,0),period=4))
m1
plot.ts(cc,col="red")
lines(fitted(m1),col="blue")

plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))

plot(m1,n.ahead=4,type='b')
mse[[1]][2]=sum((unlist(m1[8]))^2)/length(cc)
```
#分段#

```{r}
cc=x$V3
cc1=cc[1:70]
cc2=cc[96:196]

plot.ts(cc1,type="o")


acf(cc1)
pacf(cc1)

cc1=diff(cc1,lag=4)

plot.ts(cc1)

acf(cc1)
pacf(cc1)

cc=x$V3
cc1=cc[1:95]
cc2=cc[96:196]


##季節性

m1=arima(cc1,order=c(1,1,0),seasonal=list(order=c(1,1,0),period=4))
m1

plot.ts(cc1,col="red")
lines(fitted(m1),col="blue")

plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')

mse[2][1]=sum((unlist(m1[8]))^2)/length(cc1)

cc=x$V3
cc1=cc[1:95]
cc2=cc[96:196]
##原模型
m1=arima(cc1,order=c(5,0,0),seasonal=list(order=c(1,1,0),period=4)　)
m1

plot.ts(cc1,col="red")
lines(fitted(m1),col="blue")

plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')

mse[[2]][2]=sum((unlist(m1[8]))^2)/length(cc1)
```


##後段##
```{r}

plot.ts(cc2,type="o")
acf(cc2)
pacf(cc2)

cc2=diff(cc2,lag=4)
plot.ts(cc2)
acf(cc2)
pacf(cc2)

cc1=cc[1:95]
cc2=cc[96:196]

m1=arima(cc2,order=c(0,0,1),seasonal=list(order=c(1,1,0),period=4))
plot.ts(cc2,col="red")
lines(fitted(m1),col="blue")
plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')

mse[3][1]=sum((unlist(m1[8]))^2)/length(cc2)
##ma3
m1=arima(cc2,order=c(0,0,3),seasonal=list(order=c(1,1,0),period=4))
m1

plot.ts(cc2,col="red")
lines(fitted(m1),col="blue")


plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')
mse[[3]][2]=sum((unlist(m1[8]))^2)/length(cc2)

##原模型
m1=arima(cc2,order=c(5,0,0),seasonal=list(order=c(1,1,0),period=4))
m1


plot.ts(cc2,col="red")
lines(fitted(m1),col="blue")
plot(rstandard(m1))
abline(h=c(2,-2))

qqnorm(rstandard(m1))
qqline(rstandard(m1))

acf(rstandard(m1))
pacf(rstandard(m1))
plot(m1,n.ahead=20,type='b')

mse[[3]][3]=sum((unlist(m1[8]))^2)/length(cc2)
mse
```

